name: Deno CI

on: [push, pull_request]

jobs:
  test:
    name: Test app

    runs-on: ubuntu-latest

    steps:
     - name: Checkout repo
       uses: actions/checkout@v2

     - name: Setup Deno
       uses: denoland/setup-deno@v1
       with:
         deno-version: v1.x

     - name: Check format
       run: deno fmt --check

     - name: Check lint
       run: deno lint

     - name: Run tests
       run: deno test
