name: Deno CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Test app

    runs-on: ubuntu-latest

    steps:
     - name: Checkout repo
       uses: actions/checkout@v2

     - name: Download Deno
       uses: denoland/setup-deno@v1
       with:
         deno-version: v1.x
     - name: Check format
       run: deno fmt --check

     - name: Run tests
       run: deno test
